version: '3.8'

services:
  app:
    build: .
    container_name: sql_agent_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sql_agent_db
    volumes:
      - .:/app
    command: ["python", "main.py"]

  db:
    image: postgres:15
    container_name: sql_agent_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sql_agent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
