database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: sql_agent_db

langchain:
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 150
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0

security:
  sql_injection_protection: true
  logging: true
